name: github-label-sync-action
description: Sync GitHub Labels with labels definition file.
inputs:
  allow_added_labels:
    default: "false"
    description: Allow additional labels in the repository, and don't delete them.
    required: false
  github_token:
    default: ${{ github.token }}
    description: GitHub access token to sync labels.
    required: false
  source_path:
    default: .github/labels.yaml
    description: File path to find labels definition file.
    required: false
  source_repository:
    default: ${{ github.repository }}
    description: GitHub repository to find labels definition file.
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ inputs.github_token }}
        repository: ${{ inputs.source_repository }}
        sparse-checkout: ${{ inputs.source_path }}
    - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a
      with:
        config-file: ${{ inputs.source_path }}
        delete-other-labels: ${{ inputs.allow_added_labels == 'false' }}
        dry-run: true
        token: ${{ inputs.github_token }}
branding:
  color: orange
  icon: refresh-cw
